features:
  numeric:
    - tenure_months
    - age
    - active_days_last_month
    - marketing_emails_opened
    - support_calls
    - complaints_last_3m
    - late_payments
    - usage_minutes
    - monthly_charges

  categorical:
    - region
    - payment_method
    - contract_type

  target: churn
  period: period


config:
  data_raw: "../data/external/customer_churn_temporal_dataset.csv"
  random_state: 42

mlflow:
  experiment_name: Proyecto-3-prediccion-churn
  tracking_uri: https://dagshub.com/davidrodriguez2712/proyecto-3-prediccion-churn.mlflow
  model_name: proyecto-churn